spring.application.name=PasarelaDePagos

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=8090


logging.level.org.springframework.security=DEBUG
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=None


server.forward-headers-strategy=framework
server.servlet.context-path=/api/pasarela




